"""initial

Revision ID: 50ab44a4c66c
Revises: 
Create Date: 2026-03-12 23:56:50.482778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ab44a4c66c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_auth_users_id'), 'auth_users', ['id'], unique=False)
    op.create_index(op.f('ix_auth_users_username'), 'auth_users', ['username'], unique=True)
    op.create_table('content_generation_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_task_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('task_status', sa.String(), nullable=False),
    sa.Column('task_result', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_generation_tasks_unique_task_id'), 'content_generation_tasks', ['unique_task_id'], unique=True)
    op.create_index(op.f('ix_content_generation_tasks_user_id'), 'content_generation_tasks', ['user_id'], unique=False)
    op.create_table('user_file_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_file_metadata_id'), 'user_file_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_user_file_metadata_user_id'), 'user_file_metadata', ['user_id'], unique=False)
    op.create_table('user_social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('social_platform', sa.String(), nullable=False),
    sa.Column('app_password', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_social_accounts_user_id'), 'user_social_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_social_accounts_user_id'), table_name='user_social_accounts')
    op.drop_table('user_social_accounts')
    op.drop_index(op.f('ix_user_file_metadata_user_id'), table_name='user_file_metadata')
    op.drop_index(op.f('ix_user_file_metadata_id'), table_name='user_file_metadata')
    op.drop_table('user_file_metadata')
    op.drop_index(op.f('ix_content_generation_tasks_user_id'), table_name='content_generation_tasks')
    op.drop_index(op.f('ix_content_generation_tasks_unique_task_id'), table_name='content_generation_tasks')
    op.drop_table('content_generation_tasks')
    op.drop_index(op.f('ix_auth_users_username'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_id'), table_name='auth_users')
    op.drop_table('auth_users')
    # ### end Alembic commands ###
