"""initial

Revision ID: f94324c3c956
Revises: 
Create Date: 2026-03-11 22:50:45.597000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94324c3c956'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_generation_tasks', sa.Column('question', sa.String(), nullable=False))
    op.alter_column('user_file_metadata', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_social_accounts', 'app_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_social_accounts', 'handle',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_social_accounts', 'handle',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_social_accounts', 'app_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_file_metadata', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('content_generation_tasks', 'question')
    # ### end Alembic commands ###
